version: "2"

run:
  timeout: 3m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
